### ISSUE TITLE
In your README.md, youtube video label is not working

### ISSUE THREAD

**Issue by shinkeonkim** [ParkGil-hyeon/ROS-AutoDriving#1]
In first case, you can write like this
`[![Video Label](http://img.youtube.com/vi/JnRaTO2-fpo/2.jpg)](https://www.youtube.com/watch?v=JnRaTO2-fpo?t=0s) 자율 주행 완주 후 장애물 앞 정지 영상`

then, result:
[![Video Label](http://img.youtube.com/vi/JnRaTO2-fpo/2.jpg)](https://www.youtube.com/watch?v=JnRaTO2-fpo?t=0s) 자율 주행 완주 후 장애물 앞 정지 영상

**Comment by ureChanger** [comment]
good feedback
